/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_renatovarela;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Asus Pc
 */
public class Clash_royal extends javax.swing.JFrame {

    /**
     * Creates new form Clash_royal
     */
    public Clash_royal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreuser = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jd_agregarUser = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        tf_contrasena = new javax.swing.JTextField();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        tf_color = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jd_clan = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreclan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbb_lider = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbb_tipo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        Unirse_clan = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        Cartas = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        tf_dano = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_puntosvida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbb_tipoCarta = new javax.swing.JComboBox<>();
        tf_NombreCartas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Mazos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_cartas = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        cbb_Cartas = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_mazosXD = new javax.swing.JTree();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre de Usuario");

        jLabel2.setText("Contrasena");

        jButton1.setText("Iniciar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Login");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jButton1)))
                        .addGap(68, 68, 68)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreuser, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(tf_contra))))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel3)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(59, 59, 59)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Nombre de Usuario");

        jLabel7.setText("Contrasena");

        jLabel8.setText("Fecha de nacimiento");

        jLabel10.setText("Color");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Crear Un Usuario");

        jButton3.setText("Guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarUserLayout = new javax.swing.GroupLayout(jd_agregarUser.getContentPane());
        jd_agregarUser.getContentPane().setLayout(jd_agregarUserLayout);
        jd_agregarUserLayout.setHorizontalGroup(
            jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarUserLayout.createSequentialGroup()
                .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarUserLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(58, 58, 58)
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre)
                                .addComponent(tf_apellido)
                                .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(tf_contrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addComponent(jd_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_color)))
                    .addGroup(jd_agregarUserLayout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel11))
                    .addGroup(jd_agregarUserLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButton3)))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jd_agregarUserLayout.setVerticalGroup(
            jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarUserLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addGap(55, 55, 55)
                .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_agregarUserLayout.createSequentialGroup()
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8))
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_agregarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(jButton3)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel9.setText("Nombre del Clan");

        jLabel12.setText("Fecha de Creacion");

        jLabel13.setText("Usuario Lider");

        jLabel14.setText("Tipo");

        cbb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro", "Legendario" }));

        jButton4.setText("Guardar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Crear Clan");

        javax.swing.GroupLayout jd_clanLayout = new javax.swing.GroupLayout(jd_clan.getContentPane());
        jd_clan.getContentPane().setLayout(jd_clanLayout);
        jd_clanLayout.setHorizontalGroup(
            jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clanLayout.createSequentialGroup()
                .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_clanLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(53, 53, 53)
                        .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreclan)
                                .addComponent(cbb_lider, 0, 79, Short.MAX_VALUE))
                            .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_clanLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jButton4))))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jd_clanLayout.setVerticalGroup(
            jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(48, 48, 48)
                .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreclan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbb_lider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jButton4)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jList2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Unirse A un Clan");

        javax.swing.GroupLayout Unirse_clanLayout = new javax.swing.GroupLayout(Unirse_clan.getContentPane());
        Unirse_clan.getContentPane().setLayout(Unirse_clanLayout);
        Unirse_clanLayout.setHorizontalGroup(
            Unirse_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Unirse_clanLayout.createSequentialGroup()
                .addGroup(Unirse_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Unirse_clanLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Unirse_clanLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel16)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        Unirse_clanLayout.setVerticalGroup(
            Unirse_clanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Unirse_clanLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jLabel17.setText("Dano");

        tf_dano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_danoActionPerformed(evt);
            }
        });

        jLabel18.setText("Puntos de Vida");

        tf_puntosvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_puntosvidaActionPerformed(evt);
            }
        });

        jLabel20.setText("Nombre de la carta");

        cbb_tipoCarta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Golem", "Leñador", "Dragon_Infernal", "Dragon", "Gigante_Noble", "Pandilla_Duendes" }));

        jLabel19.setText("Tipo");

        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Agregar Cartas");

        javax.swing.GroupLayout CartasLayout = new javax.swing.GroupLayout(Cartas.getContentPane());
        Cartas.getContentPane().setLayout(CartasLayout);
        CartasLayout.setHorizontalGroup(
            CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartasLayout.createSequentialGroup()
                .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CartasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(41, 41, 41)
                        .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_puntosvida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_tipoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_NombreCartas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(tf_dano, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(CartasLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton5))
                    .addGroup(CartasLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel21)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        CartasLayout.setVerticalGroup(
            CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addGap(43, 43, 43)
                .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_NombreCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_puntosvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbb_tipoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(68, 68, 68)
                .addComponent(jButton5)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jl_cartas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_cartas);

        jLabel22.setText("Cartas");

        jButton6.setText("Agregar Carta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Agregar Mazo");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MazosLayout = new javax.swing.GroupLayout(Mazos.getContentPane());
        Mazos.getContentPane().setLayout(MazosLayout);
        MazosLayout.setHorizontalGroup(
            MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MazosLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MazosLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(88, 88, 88)
                        .addComponent(cbb_Cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton6)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MazosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(336, 336, 336))
        );
        MazosLayout.setVerticalGroup(
            MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MazosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbb_Cartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton7)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_mazosXD.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_mazosXD);

        jButton8.setText("Actualizar Arbol");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jMenu1.setText("Agregar");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jMenu1.add(login);

        jMenuItem3.setText("Crear Carta");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("CrearClan");
        jMenuItem1.setEnabled(false);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clan");

        jMenuItem2.setText("Unirse a un Clan");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mazo");

        jMenuItem4.setText("Crear Mazo");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton8)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_agregarUser.setModal(true);
        jd_agregarUser.pack();
        jd_agregarUser.setLocationRelativeTo(this);
        jd_agregarUser.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nombre;
        String apellido;
        String nombre_usuario;
        String contrasena;
        Date fecha_nacimiento;
        double edad;
        String color;

        nombre = tf_nombre.getText();
        apellido = tf_apellido.getText();
        nombre_usuario = tf_usuario.getText();
        contrasena = tf_contrasena.getText();
        fecha_nacimiento = jd_fecha.getDate();
        edad = (fecha_nacimiento.getTime())/(1000*60*60*24*360);
        color = tf_color.getText();
        
        users.add(new Usuarios(nombre, apellido, nombre_usuario, contrasena, fecha_nacimiento, edad, color));
       
        /*
        ontacto x = new contacto(codigo,nombre,sexo,fecha,o,direccion,idioma,h1,h2,h3,h4,h5);
                        contacto.add(x);
                        
                  
                        
                            DefaultComboBoxModel modelo =  (DefaultComboBoxModel)cb_amigos.getModel();
                            modelo.addElement(x);
                            cb_amigos.setModel(modelo);
        
        
        */
        
         DefaultComboBoxModel modelo =  (DefaultComboBoxModel)cbb_lider.getModel();
        modelo.addElement(new Usuarios(nombre, apellido, nombre_usuario, contrasena, fecha_nacimiento, edad, color));
        cbb_lider.setModel(modelo);
        
        
       tf_nombre.setText("");
       tf_apellido.setText("");
       tf_usuario.setText("");
       tf_contrasena.setText("");
       jdc_fecha.setDate(new Date());
       tf_color.setText("");

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        if (users.isEmpty()) {
            JOptionPane.showMessageDialog(jd_agregarUser, "No hay ningun usuario agregado");
        }else{
        
        for (int i = 0; i < users.size(); i++) {
            
            if (tf_nombreuser.equals(users.get(i).getNombre_usuario()) && tf_contra.equals(users.get(i).getContrasena())) {
                
                user = i;
                /*
                
                
                
                */
                
               /* jd_clan.setEnabled(true);
                jd_agregarUser.setEnabled(true);
                Mazos.setEnabled(true);
                Cartas.setEnabled(true);
                jd_login.setVisible(false);*/
                
            }
        }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre;
        Date fecha_creacion;
       String usuario_lider;
        String tipo;
        //ArrayList<Usuarios> usuarios = new ArrayList();
        
        nombre = tf_nombreclan.getText();
        fecha_creacion = jdc_fecha.getDate();
        usuario_lider = cbb_lider.getSelectedItem().toString();
        tipo = cbb_tipo.getSelectedItem().toString();
        
        clan.add(new Clan(nombre, fecha_creacion, usuario_lider, tipo));
        
        
        
    
    
    }//GEN-LAST:event_jButton4MouseClicked

    private void tf_danoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_danoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_danoActionPerformed

    private void tf_puntosvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_puntosvidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_puntosvidaActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
     String nombre;
    int dano;
    int puntos_vida;
    String objetivos;
    String velocidad;
    double coste;
     nombre = tf_NombreCartas.getText();
     /*
   Minipekka 
Montapuerco 
Golem 
Leñador 
Dragon_Infernal 
Dragon 
Gigante_Noble 
Pandilla_Duendes 
     
     */
     
     nombre = tf_NombreCartas.getText();
     dano = Integer.parseInt(tf_dano.getText());
     puntos_vida = Integer.parseInt(tf_puntosvida.getText());
     
     DefaultComboBoxModel modelo =  (DefaultComboBoxModel)cbb_Cartas.getModel();
      DefaultListModel modelo2 = (DefaultListModel) jl_cartas.getModel();
       
    
        if (cbb_tipoCarta.getSelectedItem().equals("Minipekka")) {
            cartas.add(new Minipekka(nombre, dano, puntos_vida,"", "",0));
             modelo.addElement(new Minipekka(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Montapuerco")) {
            cartas.add(new Montapuerco(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Montapuerco(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Golem")) {
            cartas.add(new Golem(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Golem(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Leñador")) {
            cartas.add(new Lenador(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Lenador(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Dragon_Infernal")) {
            cartas.add(new Dragon_Infernal(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Dragon_Infernal(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Dragon")) {
            cartas.add(new Dragon(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Dragon(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Gigante_Noble")) {
            cartas.add(new Gigante_noble(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Gigante_noble(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        if (cbb_tipoCarta.getSelectedItem().equals("Pandilla_Duendes")) {
            cartas.add(new Pandilla_duendes(nombre, dano, puntos_vida,"", "",0));
            modelo.addElement(new Pandilla_duendes(nombre, dano, puntos_vida,"", "",0));
        cbb_lider.setModel(modelo);
        }
        
        jl_cartas.setModel(modelo2);
       
     
     tf_NombreCartas.setText("");
     tf_dano.setText("");
     tf_puntosvida.setText("");
     
    
    
    
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Cartas.setModal(true);
        Cartas.pack();
        Cartas.setLocationRelativeTo(this);
        Cartas.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       DefaultListModel modelo = (DefaultListModel) jl_cartas.getModel();
       
       modelo.addElement(cbb_lider.getSelectedItem());
       jl_cartas.setModel(modelo);
       mazo.getCartas().add((Cartas)cbb_lider.getSelectedItem());
        
       /* modelo.addElement(new Personas(tf_nombre2.getText(), (Integer)sp_edad.getValue() , (String)cbo_nacionalidad.getSelectedItem()));
        
        jl_personas.setModel(modelo);
        tf_nombre2.setText("");
        sp_edad.setValue(20);
        cbo_nacionalidad.setSelectedIndex(0);*/
        
        
      
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
         
        
    
             
             usuario.getMozos().add(mazo);
             //((Personas)modeloLISTA.get(jl_personas.getSelectedIndex())).getNacionalidad();  
        
  
        
        // DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Cartas(nombre, edad, nacionalidad));
        
       
        
        
      
         
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Mazos.setModal(true);
        Mazos.pack();
        Mazos.setLocationRelativeTo(this);
        Mazos.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultTreeModel modeloARBOLre = (DefaultTreeModel)jt_mazosXD.getModel();
   
        
        DefaultListModel modelo = (DefaultListModel)jl_cartas.getModel() ;
             for (int i = 0; i <  usuario.getMozos().size(); i++) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel)jt_mazosXD.getModel();
        DefaultMutableTreeNode raiz  = (DefaultMutableTreeNode)modeloARBOL.getRoot();
        String tipo = "";
        
        int dano = (((Cartas)cartas.get(i)).getDano());
        int vida = (((Cartas)cartas.get(i)).getPuntos_vida());
        String nombre = (((Cartas)cartas.get(i)).getNombre());
             
              for (int j = 0; j < mazo.getCartas().size(); j++) {
                  if (mazo.getCartas().get(j) instanceof Especial) {
                   tipo = "Especial";
                  }
                  
                  if (mazo.getCartas().get(j) instanceof Comun) {
                      tipo = "Comun";
                      
                  }
                  if (mazo.getCartas().get(j) instanceof Legendaria) {
                        
                      tipo = "Legendaria";
                  }
                  
                  if (mazo.getCartas().get(j) instanceof Epica) {
                         tipo = "Epica";
                      
                  }
                  
                  //DefaultMutableTreeNode e = new DefaultMutableTreeNode(tipo);
                   int c = -1;
                  for (int x = 0; x < raiz.getChildCount() ; x++) {
                      if (raiz.getChildAt(x).toString().equals(tipo)) {
                          for (int k = 0; k < raiz.getChildAt(x).getChildCount(); k++) {
                              if (raiz.getChildAt(x).getChildAt(k).toString().equals(nombre) && raiz.getChildAt(x).getChildAt(k).toString().equals(tipo) ) {
                                  x = raiz.getChildCount();
                                  k = raiz.getChildAt(x).getChildAt(k).getChildCount();
                              }
                          }
                          
                          DefaultMutableTreeNode cart = new DefaultMutableTreeNode(new Cartas(nombre,dano,vida,"","",0) );
                          ((DefaultMutableTreeNode)raiz.getChildAt(x)).add(cart);
                          c = 1;
                      }
                
            }
                  
                  if (c == -1) {
                      DefaultMutableTreeNode n = new DefaultMutableTreeNode(tipo);
                       DefaultMutableTreeNode cart = new DefaultMutableTreeNode(new Cartas(nombre,dano,vida,"","",0) );
                       n.add(cart);
                       raiz.add(n);
                  }
                 
                  modeloARBOL.reload();
                  
            }
              
              
        
        }
        
       modelo.removeAllElements();
        jl_cartas.setModel(modelo);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clash_royal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clash_royal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clash_royal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clash_royal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clash_royal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Cartas;
    private javax.swing.JDialog Mazos;
    private javax.swing.JDialog Unirse_clan;
    private javax.swing.JComboBox<String> cbb_Cartas;
    private javax.swing.JComboBox<String> cbb_lider;
    private javax.swing.JComboBox<String> cbb_tipo;
    private javax.swing.JComboBox<String> cbb_tipoCarta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_agregarUser;
    private javax.swing.JDialog jd_clan;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JDialog jd_login;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private javax.swing.JList<String> jl_cartas;
    private javax.swing.JTree jt_mazosXD;
    private javax.swing.JMenuItem login;
    private javax.swing.JTextField tf_NombreCartas;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_dano;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreclan;
    private javax.swing.JTextField tf_nombreuser;
    private javax.swing.JTextField tf_puntosvida;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    
    ArrayList<Usuarios> users = new ArrayList();
    Usuarios usuario = new Usuarios();
     ArrayList<Clan> clan = new ArrayList();
     Mazos mazo= new Mazos();
     ArrayList<Cartas> cartas = new ArrayList();
     int user = 0;

}
